apiVersion: v1
kind: Namespace
metadata:
  name: splp
  labels:
    app.kubernetes.io/name: splp
    environment: poc
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    environment: poc
---
apiVersion: v1
kind: Namespace
metadata:
  name: messaging
  labels:
    app.kubernetes.io/name: messaging
    environment: poc
---
apiVersion: v1
kind: Namespace
metadata:
  name: wso2
  labels:
    app.kubernetes.io/name: wso2
    environment: poc
